name: nectarchain
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.9
  - ctapipe=0.19
  - ctapipe-io-nectarcam
  - jinja2=3.0.1
  - jupyterlab
  - jupytext
  - pre-commit
  - pytest-runner
  - pip
  - pandas
  - scipy=1.11
  - numba~=0.56.0
  - pip:
      - zeo
      - zodb
      - mechanize
      - browser-cookie3
