name: nectarchain
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.8 # nail the python version, so conda does not try upgrading / downgrading
  - ctapipe=0.19.1
  - ctapipe-io-nectarcam
  - jupyterlab
  - pytest-runner
  - pip
  - pandas
  - pip:
      - mechanize
      - browser-cookie3
