name: nectarchain
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8 # nail the python version, so conda does not try upgrading / downgrading
  - ctapipe=0.12
  - ctapipe-io-nectarcam=1.0.2
  - numpy=1.22 # higher versions >=1.23 don't work due to astropy4 dependency in ctapipe0.12
  - jinja2=3.0.1
  - jupyterlab
  - protozfits=2.0
  - pytables>=3.7
  - pytest-runner
  - pip
  - pandas
  - zeo
  - zodb
  - pip:
      - mechanize
      - browser-cookie3
