# A conda environment with all necessary packages for nectarchain developers
name: nectarchain-dev
channels:
  - default
dependencies:
  - python=3.7  # nail the python version, so conda does not try upgrading / downgrading
  - pip
  - pip:
      - https://github.com/cta-sst-1m/protozfitsreader/archive/v1.4.2.tar.gz
      - git+git://github.com/cta-observatory/ctapipe.git
      - git+git://github.com/cta-observatory/ctapipe-extra.git
      - git+git://github.com/cta-observatory/ctapipe_io_nectarcam.git
