name: nectarchain
channels:
  - default
  - conda-forge
dependencies:
  - python=3.11
  - ctapipe=0.19.1
  - ctapipe-io-nectarcam
  - jupyterlab
  - jupytext
  - pre-commit
  - protozfits=2.0
  - pytables>=3.7
  - pytest-runner
  - pip
  - pandas
  - pip:
      - mechanize
      - browser-cookie3
